version: '3.7'

services:
  go:
    container_name: go-api
    build: ./Docker/Golang
    volumes:
      - .:${GO_PROJECT_DIR}
    ports:
      - "${GO_PORT}:${GO_PORT}"
    links:
      - mysql
    env_file:
      - .env
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/Go-Api"
    networks:
      - golang

  # migrate:
  #   container_name: migrate
  #   image: migrate/migrate
  #   volumes:
  #     - .:/migrations
  #   command: ["-path", "/migrations", "-database",  "${DB_URI}", "up", "3"]
  #   links:
  #     - mysql
  #   networks:
  #     golang:
  #       aliases:
  #         - database

  mysql:
    container_name: go-mysql
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - go-mysql:/var/lib/mysql
    networks:
      - golang

  redis:
    container_name: go-redis
    image: redis:5.0.8-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - go-redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - golang

networks:
  golang:
volumes:
  go-mysql:
  go-redis:
