version: '3.7'

services:
  go:
    container_name: ${PROJECT_NAME}-api
    build: ./Docker/Golang
    volumes:
      - .:${GO_PROJECT_DIR}
    ports:
      - "${GO_PORT}:${GO_PORT}"
    links:
      - mysql
    env_file:
      - .env
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/Go-Api"
    networks:
      - golang

  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
    command: --default-authentication-plugin=mysql_native_password
      - go-mysql:/var/lib/mysql
    networks:
      - golang

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:5.0.8-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - go-redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - golang

networks:
  golang:
volumes:
  go-mysql:
  go-redis:
