version: '3.8'

services:
  spring-boot:
    build:
      context: ./docker/java
      dockerfile: Dockerfile  
      args:
        JAVA_VERSION: ${JAVA_VERSION}
    container_name: ${PROJECT_NAME}-API
    working_dir: /app
    command: sh /scripts/run.sh
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - ${API_PORT}:8080
    networks:
      - spring

  database-mysql:
    image: mysql:8
    container_name: ${PROJECT_NAME}-Database
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - spring-mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - spring

  database-postgres:
    image: postgres:14.1-alpine
    container_name: ${PROJECT_NAME}-DB
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - spring-postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - spring

networks:
  spring:

volumes:
  spring-mysql:
  spring-postgres:
