version: '3.7'

networks:
  symfony:

services:
  mysql:
    image: mysql:5.7
    container_name: symfony-mysql
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - symfony-data:/var/lib/mysql
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - symfony

  php:
    build:
      context: ./Docker/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: symfony-backend
    env_file:
      - .env
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - symfony

  yarn:
    container_name: symfony-yarn
    build:
      context: ./symfony
      dockerfile: ../Docker/Yarn/Dockerfile
    volumes:
      - ./symfony:/app
    networks:
      - symfony

  webpack:
    container_name: symfony-webpack
    build:
      context: ./symfony
      dockerfile: ../Docker/yarn/Dockerfile
    command: encore dev --watch
    volumes:
      - ./symfony:/app
    depends_on:
      - php
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-admin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - "8884:80"
    links:
      - mysql
    networks:
      - symfony

volumes:
  symfony-data:
