version: '3.7'

networks:
  symfony:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: symfony-nginx
    ports:
      - "4600:80"
    volumes:
      - ./symfony:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - symfony

  php:
    build:
      context: ./Docker/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: symfony-backend
    env_file:
      - .env
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - symfony

  yarn:
    container_name: symfony-yarn
    build:
      context: ./symfony
      dockerfile: ../Docker/yarn/Dockerfile
    volumes:
      - ./symfony:/app
    networks:
      - symfony

  webpack:
    container_name: symfony-webpack
    build:
      context: ./symfony
      dockerfile: ../Docker/yarn/Dockerfile
    command: encore dev --watch
    volumes:
      - ./symfony:/app
    depends_on:
      - php
    networks:
      - symfony

  mysql:
    image: mysql:8
    container_name: symfony-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - symfony-data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-admin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - "4601:80"
    links:
      - mysql
    networks:
      - symfony

volumes:
  symfony-data:
