version: '3.6'

services:
  redis:
    container_name: redis
    image: redis:5.0.8-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - redis

networks:
  redis:

volumes:
  redis-data:
