version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    ports:
      - "${WEBSERVER_PORT}:80"
    networks:
      - laravel

  php:
    build:
      context: ./src
      dockerfile: ../docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PUID: ${UID}
    container_name: ${PROJECT_NAME}-backend
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "${FPM_PORT}:9000"
    networks:
      - laravel

  npm:
    image: node:${NODE_VERSION}
    container_name: ${PROJECT_NAME}-npm
    env_file:
      - .env
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-mysql
    tty: true
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - laravel-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - laravel

volumes:
  laravel-data:

networks:
  laravel:
