version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PUID: ${UID}
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - database
    links:
      - database
    networks:
      - laminas

  database:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-database
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - laminas-data:/var/lib/mysql
    networks:
      - laminas

networks:
  laminas:

volumes:
  laminas-data:
