version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PUID: ${UID}
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '4400:80'
    depends_on:
      - database
    links:
      - database
    networks:
      - laminas

  database:
    image: mysql:8
    container_name: ${PROJECT_NAME}-database
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - laminas-data:/var/lib/mysql
    networks:
      - laminas

networks:
  laminas:

volumes:
  laminas-data:
