ARG PHP_VERSION
FROM php:${PHP_VERSION}

RUN apt update && apt install -y \
    libicu-dev

RUN docker-php-ext-configure \
    intl

RUN docker-php-ext-install \
    intl \
    pdo \
    pdo_mysql \
    mysqli

RUN a2enmod rewrite
RUN a2enmod actions
COPY apache2.conf /etc/apache2/
RUN service apache2 restart

# CodeIgniter requires the PHP additions to be in place, even when creating a project
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

ARG PUID=1000
RUN useradd -G www-data,root -u $PUID -d /home/devuser devuser
RUN mkdir -p /home/devuser/.composer && \
    chown -R devuser:devuser /home/devuser
