version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - databases
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - databases
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    depends_on:
      - mysql
      - mariadb
    environment:
      PMA_HOSTS: mysql,mariadb
    ports:
      - 8880:80
    links:
      - mysql
      - mariadb
    networks:
      - databases
  postgres:
    container_name: postgres
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - databases
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.19
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8881:80
    networks:
      - databases
networks:
  databases:
volumes:
  mysql-data:
  postgresql-data:
  mariadb-data:
