version: '3.8'

services:
  php:
    build:
      context: ./src
      dockerfile: ../docker/Dockerfile
    container_name: ${PROJECT_NAME}-application
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/webroot
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "${WEBSERVER_PORT}:8080"
    depends_on:
      - mysql
      - postgres
    links:
      - mysql
      - postgres
    networks:
      - cake

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - cake-mysql-data:/var/lib/mysql
    networks:
      - cake

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${PROJECT_NAME}-postgresql
    env_file:
      - .env
    volumes:
      - cake-postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - cake

networks:
  cake:

volumes:
  cake-mysql-data:
  cake-postgres-data:
