version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: cake-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - database
    links:
      - database
    networks:
      - cake

   cake:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      args:
        PHP_CLI_VERSION: ${PHP_CLI_VERSION}
    container_name: cake-cli
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    entrypoint: bin/cake
    networks:
      - cake

 nginx:
    image: nginx:stable-alpine
    container_name: cake-nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - cake

  database:
    image: mysql:8
    container_name: cake-database
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - cake-data:/var/lib/mysql
    networks:
      - cake

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cake-admin
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - '8884:80'
    links:
      - database
    networks:
      - cake

networks:
  cake:

volumes:
  cake-data:
