version: '3.7'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: collection-tracker-application
    env_file:
      - .env
    volumes:
      - ./php:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - database
    links:
      - database
    networks:
      - collection-tracker

  nginx:
    image: nginx:stable-alpine
    container_name: collection-tracker-nginx
    ports:
      - '8080:80'
    volumes:
      - ./php:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - collection-tracker

  database:
    image: ghcr.io/linuxserver/mariadb:alpine-version-10.5.9-r0
    container_name: collection-tracker-database
    ports:
      - '3306:3306'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Budapest
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - collection-data:/var/lib/mysql
    networks:
      - collection-tracker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: collection-tracker-admin
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - '8884:80'
    links:
      - database
    networks:
      - collection-tracker

networks:
  collection-tracker:

volumes:
  collection-data:
