version: '3.8'

services:
  php:
    build:
      context: ./src
      dockerfile: ../docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - mysql
      - postgres
    links:
      - mysql
      - postgres
    networks:
      - cake

  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - postgres
    networks:
      - cake

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - cake-mysql-data:/var/lib/mysql
    networks:
      - cake

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${PROJECT_NAME}-postgresql
    env_file:
      - .env
    volumes:
      - cake-postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - cake

networks:
  cake:

volumes:
  cake-mysql-data:
  cake-postgres-data:
