version: '3.7'

services:
  django:
    container_name: ${PROJECT_NAME}-Django
    build:
      context: ./docker/python
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    networks:
      - django

  db:
    container_name: ${PROJECT_NAME}-DB
    image: postgres:12.2-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB: ${POTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - django-db:/var/lib/postgresql/data
    networks:
      - django

networks:
  django:
volumes:
  django-db:
