version: '3.7'

services:
  django:
    container_name: Pollster-Django
    build:
      context: .
      dockerfile: Docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    networks:
      - django

  db:
    container_name: Pollster-DB
    image: postgres:12.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pollster-db:/var/lib/postgresql/data
    networks:
      - django

networks:
  django:
volumes:
  pollster-db:
