version: '3.8'

services:
  angular:
    container_name: ${PROJECT_NAME}-Client
    build:
      context: ./docker/angular
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    env_file:
      - .env
    volumes:
      - ./client:/app
    working_dir: /app
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    networks:
      - angular

networks:
  angular:
