version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PUID: ${UID}
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '4200:80'
    depends_on:
      - database
    links:
      - database
    networks:
      - codeigniter

  spark:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      args:
        PUID: ${UID}
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-spark
    env_file:
      - .env
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./src:/var/www/html
    entrypoint: php spark
    networks:
      - codeigniter

  phpunit:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      args:
        PHP_CLI_VERSION: ${PHP_CLI_VERSION}
    container_name: ${PROJECT_NAME}-phpunit
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    entrypoint: vendor/bin/phpunit
    networks:
      - codeigniter

  database:
    image: mysql:8
    container_name: ${PROJECT_NAME}-database
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - codeigniter-data:/var/lib/mysql
    networks:
      - codeigniter

networks:
  codeigniter:

volumes:
  codeigniter-data:
