version: '3.7'

services:
  rails:
    container_name: PM-Rails
    build:
      context: .
      dockerfile: Docker/Rails-With-Yarn/Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        BUNDLE_JOBS: 15
        BUNDLE_RETRY: 2
        INSTALL_PG_CLIENT: 'true'
        UID: 1000
        GID: 1000
    env_file: .env
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    entrypoint: Docker/Rails-With-Yarn/entrypoint.sh
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    user: ruby
    tty: true
    stdin_open: true
    links:
      - postgres
      - mailhog
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - pm-rails

  console:
    container_name: PM-Rails-Console
    build:
      context: .
      dockerfile: Docker/Rails-Simple/Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        UID: 1000
        GID: 1000
    env_file: .env
    command: bundle exec rails c
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    user: ruby
    tty: true
    stdin_open: true
    networks:
      - pm-rails

  postgres:
    container_name: PM-Rails-DB
    image: postgres:12.2-alpine
    env_file: .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - rails-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pm-rails

  redis:
    container_name: PM-Rails-Redis
    image: redis:5.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - rails-redis:/data
    entrypoint: redis-server --appendonly yes
    networks:
      - pm-rails

  mailhog:
    container_name: Rails-Mailhog
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none
    networks:
      - pm-rails

networks:
  pm-rails:
volumes:
  rails-db:
  rails-redis:
  gems:
  node_modules:
  packs:
  rails_cache:
