version: '3.7'
services:
  rails:
    container_name: Rails-Backend
    build:
      context: ./Rails-Backend
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.5.1'
    command:
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./Rails-Backend:/app
    ports:
      - '3000:3000'
    networks:
      - rails

  db:
    container_name: Rails-DB
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: 'auth'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - rails-db:/var/lib/postgresql/data
    networks:
      - rails

networks:
  rails:
volumes:
  rails-db:
