version: '3.7'
services:
  rails:
    container_name: Rails
    build:
      context: ./Rails-Backend
      dockerfile: ../Docker/Rails-With-Yarn/Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./Rails-Backend:/app
    links:
      - db
    depends_on:
      - db
      - yarn
    ports:
      - '3000:3000'
    networks:
      - rails

  yarn:
    container_name: Yarn
    build:
      context: ./Rails-Backend
      dockerfile: ../Docker/Yarn/Dockerfile
    volumes:
      - ./Rails-Backend:/app
    networks:
      - rails

  db:
    container_name: DB
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: 'auth'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - rails

networks:
  projekt:
volumes:
  db:
